version: '3.8'

services:
  mydb-mongo:               # e.g., mydb-mongo
    image: mongo:6.0
    container_name: project-mongo
    restart: on-failure
    ports:
      - "27018:27017"
    volumes:
      - mydb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: s3cr3t
      MONGO_INITDB_DATABASE: users
      TZ: Asia/Karachi
    networks:
      - mypaas-net

volumes:
  mydb_data:

networks:
  mypaas-net:
    external: true
